language: swift

branches:
 only:
 - master

xcode_project: EZSwiftExtensions.xcodeproj
xcode_scheme: EZSwiftExtensions-iOS
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.1

script:
- xcodebuild clean build test -project EZSwiftExtensions.xcodeproj -scheme EZSwiftExtensions-iOS

notifications:
  email: false
