language: objective-c

branches:
 only:
 - master

xcode_project: EZSwiftExtensions.xcodeproj
xcode_scheme: EZSwiftExtensionsTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.1

script:
- xcodebuild clean build test -project EZSwiftExtensions.xcodeproj -scheme EZSwiftExtensionsTests
